# Generated by Django 2.2 on 2019-06-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_auto_20190607_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='completed',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
